version: "3.7"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env
    volumes:
      - ./data:/home/data
      - ./tmp:$TMP_DIR
    restart: unless-stopped
    ports:
      - "4242:8000"
